# Generated by Django 2.2.6 on 2023-05-08 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20230508_1837'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
